const tricksDatabase = {
    "t_raw_math": { "title": "Basic Arithmetic", "text": "Pure arithmetic calculation. Do the mental math left-to-right as quickly as possible." },
    "t_order_of_operations": { "title": "Order of Operations", "text": "Follow PEMDAS. 1) Parentheses. 2) Exponents. 3) Mult/Div. 4) Add/Sub." },
    "t_frac_add": { "title": "Adding Fractions", "text": "Multiply diagonally and add for the numerator (ad + bc). Multiply denominators for the bottom (bd)." },
    "t_perc_frac": { "title": "Percentages to Fractions", "text": "Memorize fraction families. 1/8=12.5%, 1/40=2.5%, etc." },
    "t_div_5": { "title": "Dividing by 5", "text": "Multiply by 2 and move the decimal point one place to the left." },
    "t_roman_num": { "title": "Roman Numerals", "text": "M=1000, D=500, C=100, L=50, X=10, V=5, I=1." },
    "t_arith_series": { "title": "Arithmetic Series Sum", "text": "Average the first and last term, then multiply by the number of terms." },
    "t_distributive": { "title": "Distributive Property", "text": "Break one number into easier parts. (e.g., 12 * 17 = 12 * 10 + 12 * 7)." },
    "t_cross_cancel": { "title": "Cross-Cancellation", "text": "Cancel common factors in numerators and denominators before multiplying." },
    "t_foil": { "title": "FOILing", "text": "Multiply Last digits. Multiply Inner + Outer digits. Multiply First digits." },
    "t_mult_near_100": { "title": "Multiplying Near 100", "text": "Find distances from 100. Multiply diffs for last two digits. Cross-add for first digits." },
    "t_mult_25": { "title": "Multiplying by 25", "text": "Divide by 4, multiply by 100. Remainder 1=25, 2=50, 3=75." },
    "t_negative_zero_exponents": { "title": "Negative Exponents", "text": "x^0 = 1. Negative exponent is a reciprocal: x^-n = 1 / x^n." },
    "t_gcd_lcm": { "title": "GCD and LCM", "text": "GCD(A,B) * LCM(A,B) = A * B." },
    "t_mult_end_5": { "title": "Numbers Ending in 5", "text": "If tens sum is even, ends in 25; odd, 75. Add half the sum of tens to tens product." },
    "t_unit_conversion": { "title": "Unit Conversions", "text": "1 Gal = 4 Qt = 8 Pt = 16 Cups = 128 Oz." },
    "t_div_9_trick": { "title": "Dividing by 9", "text": "Bring down first digit, add to next, repeat. Final sum is remainder." },
    "t_diff_cubes": { "title": "Difference of Cubes", "text": "(a-b)(a^2+ab+b^2) = a^3 - b^3." },
    "t_absolute_value": { "title": "Absolute Value", "text": "Work from the inside out. All negative results become positive." },
    "t_magic_14443": { "title": "Magic 14443", "text": "Memorize: 14443 * 7 = 101101." },
    "t_diff_squares": { "title": "Difference of Squares", "text": "a^2 - b^2 = (a-b)(a+b)." },
    "t_proportions": { "title": "Proportions", "text": "Set up equation A * B = C * x and simplify." },
    "t_set_intersection": { "title": "Set Intersection", "text": "Count only the elements that exist in BOTH sets." },
    "t_perfect_sq_trinomial": { "title": "Perfect Square Trinomial", "text": "a^2 - 2ab + b^2 = (a-b)^2." },
    "t_linear_equation": { "title": "Linear Equations", "text": "Group variables on one side, constants on the other." },
    "t_mult_3x3": { "title": "3x3 Multiplication", "text": "Cross-multiply moving right to left: 1, 2, 3, 2, 1 columns." },
    "t_shared_factor": { "title": "Shared Factor", "text": "Pull out a common factor before doing the math." },
    "t_exponent_rules": { "title": "Exponent Rules", "text": "Multiply bases = add exponents. Divide = subtract." },
    "t_linear_inequality": { "title": "Inequalities", "text": "Solve normally, but flip the sign if multiplying/dividing by negative." },
    "t_mult_units_10": { "title": "Units Add to 10", "text": "Multiply units. Multiply front digit by (itself + 1)." },
    "t_trig_reference_angles": { "title": "Trig Reference", "text": "Subtract 2pi until angle is on standard unit circle." },
    "t_trig_unit_circle": { "title": "Unit Circle", "text": "Recall standard values. Tan = Sin / Cos." },
    "t_alt_sum_squares": { "title": "Alternating Sum Squares", "text": "For series ending on -n^2: -[n(n+1)/2]." },
    "t_log_properties": { "title": "Log Properties", "text": "ln(e^x) = x." },
    "t_limit_ex": { "title": "Calculus Limits", "text": "lim x->0 (e^x-1)/x = 1." },
    "t_calc_power_rule": { "title": "Power Rule", "text": "f'(x) of cx^n = (c*n)x^(n-1)." },
    "t_inverse_trig": { "title": "Inverse Trig", "text": "Draw right triangle to find missing side." },
    "t_mult_11": { "title": "Multiplying by 11", "text": "Write ones digit, add consecutive digits moving left." },
    "t_sum_of_cubes": { "title": "Sum of Cubes", "text": "[n(n+1)/2]^2." },
    "t_calc_definite_integral": { "title": "Definite Integrals", "text": "Antiderivative evaluated at upper minus lower bounds." },
    "t_rational_asymptotes": { "title": "Asymptotes", "text": "Vertical where denom=0. Slant/Horiz based on degrees." },
    "t_inverse_function_point": { "title": "Inverse Functions", "text": "Set f(x) equal to value and solve for x." },
    "t_nested_logs": { "title": "Nested Logs", "text": "Evaluate inside out." },
    "t_geom_series_inf": { "title": "Infinite Geometric", "text": "S = a / (1 - r)." },
    "t_consecutive_mult": { "title": "Consecutive Mult", "text": "n*(n+1) = n^2 + n." },
    "t_diff_sq_reverse": { "title": "Reverse Diff Squares", "text": "(n-1)(n+1) = n^2 - 1." },
    "t_double_half": { "title": "Double and Half", "text": "Double one factor, halve the other." }
};
